print("  __________________")
print("< Ezt rajzold meg! >")
print(" ------------------")
print("        \   ^__^")
print("         \  (oo)\_______")
print("            (__)\       )\/\\")
print("                ||----w |")
print("                ||     ||")
